### ISSUE TITLE
Not pulling in all news articles

### ISSUE THREAD

**Issue by Radams86** [Nodragem/InSciOut-Project#6]
We've noticed that the python code to pull in the raw data doesn't read all of the columns for the trial data - it stops at column AV and we need it to go to column DA, for example.

We're just looking at the code and can't see where to edit this - could you please let us know how we can increase the number of columns that we read in 

For an example see InSciOut-Project/rawdata/trial_data/22-030 complete.xls
this only reads in 14 news articles but there are >80
i.e. list from The Daily Mail to The Sunday Times Scotland, but it should run to China daily - see Source column in News_table

The name of the columns that we need are exactly the same as the other news sources where the source is pulled in from row 7 and the column is only read in if there is a number 1 in row 8. 

I think the example above is the data sheet with the most columns but to be on the safe side could we read everything in up to column EZ

**Comment by Nodragem** [comment]
I will work on that next week, it is ok? or is this urgent?

**Comment by Radams86** [comment]
Hi Geoffrey, 

It's fairly urgent because we can't do the analysis without it - I have set Sunday aside (we have an analysis meeting with Petroc on Monday) so if at all possible to do it by then that would be great.
If you don't think that's possible please let us know.

Thanks
Rachel

**Comment by Nodragem** [comment]
Currently the code in:
`transformExcelFilesToSQLiteDatabase.py`

at line 64 is handling the number of columns to extracts from the spreadsheet:
`data_table = df.iloc[6:55, 3:48]`

Thus, for now, it extracts data up to column 48 (not included).

To change this, I think it should be enough to replace this line with:
`data_table = df.iloc[6:55, 3:]`

I will test this solution and push it if it works.

**Note for later:** the columns in each spreadsheet are representing 'journal articles/news articles' . Then, the spreadsheets are transposed so that each row is a 'journal article/news article' entry.

**Comment by Nodragem** [comment]
I think it works:
![image](https://user-images.githubusercontent.com/10520249/33373329-4658fc2a-d4f9-11e7-9ee9-97fc7282162e.png)

I will push the change and I will close this issue.
You will be able to re-open it if there is any issue with this solution.
